import type { MetadataRoute } from "next"
import { services } from "@/lib/services"
import { SITE_URL } from "@/lib/schema"

// Per-route lastmod is set to build time on every deploy. Real per-file
// tracking would require either (a) committing a generated mtime cache file
// to git, or (b) maintaining a `lastUpdated` field per service by hand. We
// deploy often enough that "every page updated today" isn't actively
// misleading, and Google treats lastmod as a soft hint anyway. If we ever
// need per-page granularity, the move is to add a content-hash cache file
// generated by a local prebuild step.
export default function sitemap(): MetadataRoute.Sitemap {
  const now = new Date()

  const staticRoutes: MetadataRoute.Sitemap = [
    { url: `${SITE_URL}/`, lastModified: now, changeFrequency: "weekly", priority: 1.0 },
    { url: `${SITE_URL}/services`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${SITE_URL}/services/waste-management`, lastModified: now, changeFrequency: "monthly", priority: 0.9 },
    { url: `${SITE_URL}/about`, lastModified: now, changeFrequency: "yearly", priority: 0.6 },
    { url: `${SITE_URL}/faq`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${SITE_URL}/jobs`, lastModified: now, changeFrequency: "weekly", priority: 0.5 },
    { url: `${SITE_URL}/jobs/apply`, lastModified: now, changeFrequency: "yearly", priority: 0.4 },
    { url: `${SITE_URL}/forms`, lastModified: now, changeFrequency: "yearly", priority: 0.5 },
    { url: `${SITE_URL}/contact`, lastModified: now, changeFrequency: "yearly", priority: 0.7 },
  ]

  const serviceRoutes: MetadataRoute.Sitemap = services.map((service) => ({
    url: `${SITE_URL}/services/${service.slug}`,
    lastModified: now,
    changeFrequency: "monthly",
    priority: service.featured ? 0.9 : 0.8,
  }))

  return [...staticRoutes, ...serviceRoutes]
}
